---
- name: create pam.scripts dir
  file:
    path: /etc/pam.scripts
    mode: 0755
    owner: "root"
    group: "root"
    state: directory
- name: Create email notification script
  template:
    src: send_mail_on_login.sh.j2
    dest: /etc/pam.scripts/send_mail_on_login.sh
    mode: 0700
    owner: "root"
    group: "root"
- name: call script from sshd login
  lineinfile:
    dest: /etc/pam.d/sshd
    line: "session optional pam_exec.so /etc/pam.scripts/send_mail_on_login.sh"
- name: setup cronjob to remove remember file
  ansible.builtin.cron:
    name: "remove pam_ssh_mail_on_login remember file every day"
    minute: 0
    hour: 0
    job: "echo -n \"\" >> {{ remember_file }}"
    state: "{{ 'present' if do_remember else 'absent' }}"
- name: create remember file
  file:
    path: "{{ remember_file }}"
    mode: 0600
    owner: "root"
    group: "root"
    state: "{{ 'touch' if do_remember else 'absent' }}"
